version: '2'
services:
  tasklist-app:
    image: tasklist
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tasklist-postgresql:5432/TaskList
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  tasklist-postgresql:
    extends:
      file: postgresql.yml
      service: tasklist-postgresql
